alias rc='bundle exec rails console'
alias rg='bundle exec rails generate'
alias rd='bundle exec rails destroy'
alias rs='bundle exec rails server'
alias rdb='bundle exec rails db:migrate'
alias rdb:reset='bundle exec rails db:reset'
alias rdb:rollback='bundle exec rails db:rollback'
alias rdb:rollback:all='bundle exec rails db:rollback:all'
alias rdb:rollback:step='bundle exec rails db:rollback:step'
alias rdb:rollback:step:all='bundle exec rails db:rollback:step:all'
alias rdb:rollback:step:all='bundle exec rails db:rollback:step:all'
alias spec='bundle exec rspec'
alias spec:watch='bundle exec rspec --watch'
alias spec:focus='bundle exec rspec --focus'
alias spec:focus:watch='bundle exec rspec --focus --watch'
alias spec:focus:all='bundle exec rspec --focus --all'
alias spec:focus:all:watch='bundle exec rspec --focus --all --watch'

# RSpec alias with fail-fast (stops after first failure)
alias spec:ff='bundle exec rspec --fail-fast'
